apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: try-api
inputs:
  uri:
    required: true
  http-method:
    required: true
runs:
  using: composite
  steps:
    - id: call-api
      name: Call API
      uses: docker://golang:1.20.3-alpine3.17
      shell: sh
      run: |
        set -x
        echo "DNS URL: ${{ cloudbees.api.url }}"
        echo "Job ID: ${{ job.id }}"
        echo "Step ID: ${{ step.internal.id }}"
        echo "Run ID: ${{ cloudbees.run_id }}"
        curl -H "Authorization: Bearer ${{ cloudbees.api.token }}" "${{ cloudbees.api.url }}/${{ inputs.uri }}"