apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: try-api
inputs:
  uri:
    required: true
    type: string
  http-method:
    required: true
    type: string
  payload:
    type: string
    
runs:
  using: composite
  steps:
    - id: echo
      name: Echo something
      uses: docker://golang:1.20.3-alpine3.17
      shell: sh
      run: |
        echo "Another step from a new version 2"
    - name: Do get
      uses: docker://curlimages/curl:8.8.0
      if: inputs.http-method  == 'get'
      run: |
        echo "URL: ${{ cloudbees.api.url }}${{ inputs.uri }}"
        curl -kv -H "Authorization: Bearer ${{ cloudbees.api.token }}" "${{ cloudbees.api.url }}${{ inputs.uri }}"
    - name: Do post
      uses: docker://curlimages/curl:8.8.0
      env:
        PAYLOAD: ${{ inputs.payload }}
      if: inputs.http-method  == 'post'
      run: |
        echo "URL: ${{ cloudbees.api.url }}${{ inputs.uri }}"
        echo $PAYLOAD > /tmp/data.json
        curl -kv -X POST -H "Authorization: Bearer ${{ cloudbees.api.token }}" "${{ cloudbees.api.url }}${{ inputs.uri }}" -d @/tmp/data.json    
